# Generated by Django 2.2.28 on 2024-03-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(default='Write your review here...', max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
