# Generated by Django 2.2.28 on 2024-03-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240319_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pic.png', upload_to='profile_images'),
        ),
    ]
