# Generated by Django 2.2.28 on 2024-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240307_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_recipes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
    ]
