# Generated by Django 2.2.28 on 2024-03-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'Recipes'},
        ),
    ]
