# Generated by Django 2.2.28 on 2024-03-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240307_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='ingredients', max_length=20000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='instructions', max_length=20000),
        ),
    ]
