# Generated by Django 2.2.28 on 2024-03-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240313_1346'),
        ('recipes', '0005_auto_20240314_1735'),
    ]

    operations = [
    ]
