# Generated by Django 5.0.3 on 2024-03-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240314_1735'),
        ('recipes', '0006_auto_20240313_1346'),
    ]

    operations = [
    ]
