# Generated by Django 2.2.28 on 2024-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20240318_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_recipes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_recipes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
