# Generated by Django 5.0.3 on 2024-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_0005_auto_20240314_1735_0006_auto_20240313_1346'),
        ('recipes', '0008_auto_20240318_1504'),
    ]

    operations = [
    ]
