# Generated by Django 2.2.28 on 2024-03-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20240318_1554'),
        ('recipes', '0010_category_recipe'),
    ]

    operations = [
    ]
