# Generated by Django 2.2.28 on 2024-03-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240319_2244'),
        ('recipes', '0011_auto_20240320_1300'),
    ]

    operations = [
    ]
